#server config
server:
  port: 8080
  address: 0.0.0.0

spring:
  #DB config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sseudadb?allowMultiQueries=true
    username: sseuda
    password: sseuda

  #fileupload config
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  # MVC config
  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/sseudaimgs/

#Mybatis framework config
mybatis:
  mapper-locations: classpath:mapper/*.xml

image:
  # Local Dev
  add-resource-locations: classpath:/static/sseudaimgs/
  add-resource-handler: /sseudaimgs/**
  image-dir: src/main/resources/static/sseudaimgs/
  image-url: http://localhost:8080/sseudaimgs/

#springdoc open-api config
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# logging config
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace